### ISSUE TITLE
Ldap connect port not used

### ISSUE THREAD

**Issue by douyu** [ldaptools/ldaptools#10]
see:  [http://php.net/manual/zh/function.ldap-connect.php](url)
`
The port to connect to. Not used when using LDAP URIs.
`

**Comment by ChadSikorra** [comment]
Thanks for letting me know about this! It has been fixed with https://github.com/ldaptools/ldaptools/commit/12ae607d42831ced88be34da529707c16878e413. I really need to get tests against an actual LDAP server working with Travis. It would avoid potential issues in the connection class like this, among other things.
