### ISSUE TITLE
Where are the rest of the attributes?

### ISSUE THREAD

**Issue by rickwarren** [ldaptools/ldaptools#38]
$query = $ldap->buildLdapQuery();
$user = $query->fromUsers()
    ->where($query->filter()->eq('uid', $row['uid']))
    ->getLdapQuery()
    ->getSingleResult();

var_dump($user);

this returns only 3 attributes for the user.  firstName, lastName and dn....where are the rest of the attributes?

**Comment by ChadSikorra** [comment]
Use the "select()"  method to say what attributes you want. It only grabs a
few by default. You could do "select('*')" which grabs everything defined
in the schema configuration. Or you could do "select('**')" to select
basically everything (since when you use 'fromUsers()' it uses stuff
defined in the schema configuration).

On Sep 18, 2017 10:44 PM, "rickwarren" <notifications@github.com> wrote:

$query = $ldap->buildLdapQuery();
$user = $query->fromUsers()
->where($query->filter()->eq('uid', $row['uid']))
->getLdapQuery()
->getSingleResult();

var_dump($user);

this returns only 3 attributes for the user. firstName, lastName and
dn....where are the rest of the attributes?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ldaptools/ldaptools/issues/38>, or mute the thread

**Comment by rickwarren** [comment]
select('**')    

now only returns dn......?

**Comment by ChadSikorra** [comment]
Are you still doing 'fromUsers()' with that? Does just a single '*' return
much more? Guess I haven't tried that against OpenLDAP.

**Comment by rickwarren** [comment]
'*'  worked!  thank you!
