### ISSUE TITLE
Creating objects with empty attributes results in error

### ISSUE THREAD

**Issue by NyroTheCat** [ldaptools/ldaptools#6]
Hi Chad,

may i have found a small bug. if a new LDAP object with either an _empty string_ or _NULL_ attribute is created, it will result in an error. eg:

```php
// Creating a user account (enabled by default)
$ldapObject->createUser()
    ->in('cn=Users,dc=example,dc=local')
    ->with([
        'username' => 'jsmith',
        'sn' => ''
        'givenName' => NULL
    ])
    ->execute();
```

Result:
> LDAP Add Operation Error: Invalid syntax

a preprocessing of attributes before the ldap object is created by omitting such empty values would be an option.

**Comment by ChadSikorra** [comment]
Yeah, filtering the attributes before the operation is executed is probably the best method here. Probably `array_filter` with a callback would work fine. Should be able to put something together later today. Thanks for reporting this.

**Comment by ChadSikorra** [comment]
Fixed in https://github.com/ldaptools/ldaptools/commit/c510b9d55c206b8af8e65688cefd6f0da84efaa5. I think that's as far as I want to take it though. I'm still kinda torn about it, as there could be a lot of reasons why a null or empty string would have been set, so it might make for confusing troubleshooting if it doesn't error.
