### ISSUE TITLE
Exception on filter creation using certain attributes

### ISSUE THREAD

**Issue by NyroTheCat** [ldaptools/ldaptools#7]
Hi Chad, i found an interesting issue. It may be worth a look.

When i try to create a filter with certain attributes the following exception will be thrown:
```php
...
->where(
    $query->filter()->present('location')
)
...
```
Exception:
`Attribute "l" is not a valid name or OID.`

This is defined in my schema
```yml
...
attributes:
    location: l
...
```
I'm using openldap where the attribute name for location is called `l`. It doesn't make a difference wich filtertype is used. Another example attribute is `o` for organization name

**Comment by ChadSikorra** [comment]
Yikes...I'm surprised I never ran across this myself yet. This has been fixed in https://github.com/ldaptools/ldaptools/commit/eb0ce615da72a5b5922bcd42b41bb992a49b4c38. Thanks for reporting it! Hopefully I'll be tagging a new release soon. I'm currently redesigning the GPOLink converter, and a few other things before I do.
