### ISSUE TITLE
Case insensitive ordering

### ISSUE THREAD

**Issue by NyroTheCat** [ldaptools/ldaptools#8]
Hi Chad, i've got an idea. Would it be possible to add a parameter to the `orderBy()` method to make the ordering case insensitive? An alternative method would be also possible.

Regards
Nyro

**Comment by ChadSikorra** [comment]
I guess the easiest way to achieve this would be to do a strtolower against the values when doing the comparison for the sort. However, I think a global option to enable it might be the way to go, rather than per attribute.

Another way would be to define an interface with a single `compare` method and then that class could be set on the `LdapQuery` class prior to executing the search. Then you could do whatever you want with the comparison. I'll have to think about this a little more.

**Comment by ChadSikorra** [comment]
Resolved by https://github.com/ldaptools/ldaptools/commit/45cae018c50ba2278dff72b87a85b59674e7a248. Since everything else is case-insensitive I decided for consistency to make it sort case-insensitive by default. If you instead want to sort in a case-sensitive way you now have to do:

```
$users = $ldap->buildLdapQuery()
    ->fromUsers()
    ->orderBy('firstName')
    ->getLdapQuery()
    ->setIsCaseSensitiveSort(true)
    ->getResult();
```

I updated the query builder docs to reflect this in the orderBy section.

**Comment by ChadSikorra** [comment]
Weird...I'm seeing issues in the tests for the case-insensitive sort on PHP 5.6. I'm leaving this open for the moment. It seems to work fine in PHP 7. Not sure what the difference is yet.

**Comment by ChadSikorra** [comment]
Fixed for real now ;) https://github.com/ldaptools/ldaptools/commit/68f02bc794d989090126f2ca8d3a31cd82ae3caa . It now sorts predictably across PHP versions. Apparently the sorting behavior for `usort` is different between PHP5 and PHP7, though it is not mentioned in any of the upgrade/migration docs. Interesting find: http://stackoverflow.com/a/34288091/2242593
